name = "ens"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"
keep_vars = true

[placement]
mode = "smart"

routes = [{ pattern = "ens.ethfollow.xyz", custom_domain = true }]

kv_namespaces = [
    { binding = "ENSTATE-1", id = "c2f0cac721664128bc917e2cd0608875" },
]

[build]
command = "cargo install --quiet worker-build && worker-build --release"
