name = "ens"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"

[placement]
mode = "smart"

kv_namespaces = [
    { binding = "ENSTATE-1", id = "6d860f01a338425d85c102cda7898303" },
]

[build]
command = "cargo install --quiet worker-build && worker-build --release"

[vars]
OPENSEA_API_KEY = "05888bbd4e9848de868e854d81b9b5e2"
