name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

defaults:
  run:
    shell: bash

env:
  NAME: ens-worker
  CARGO_TERM_COLOR: always
  ACTIONS_RUNNER_DEBUG: true

jobs:
  deploy-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Get App Version
        id: version
        run: |
          export VERSION="$(jq --raw-output '.version' package.json)"
          echo "APP_VERSION=${VERSION}" >> $GITHUB_ENV

      - run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal

      - uses: Swatinem/rust-cache@v2.7.0
        with:
          prefix-key: v0 # increment this to bust the cache if needed

      - name: Install sccache
        uses: mozilla-actions/sccache-action@v0.0.3
        env:
          RUSTC_WRAPPER: sccache
          SCCACHE_GHA_ENABLED: true

      - name: Build shared
        working-directory: shared
        run: cargo build --release

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: Install Dependencies
        run: |
          bun install
          bun add --global wrangler@latest

      - name: Deploy Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: wrangler deploy
